/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AboutDialog (void);
GtkWidget* create_popup_bg (void);
GtkWidget* create_popup_object (void);
GtkWidget* create_Transparency (void);
GtkWidget* create_MatlDlg (void);
GtkWidget* create_TransDlg (void);
